import type { NavLink, Project, Experience, Testimonial, SkillGroup, Education } from '@/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '#home' },
  { label: 'About', href: '#about' },
  { label: 'Projects', href: '#projects' },
  { label: 'Skills', href: '#skills' },
  { label: 'Experience', href: '#experience' },
  { label: 'Contact', href: '#contact' },
]

export const SOCIAL_LINKS = [
  { label: 'GitHub', href: 'https://github.com/aldiero141', icon: 'github' },
  { label: 'LinkedIn', href: 'https://linkedin.com/in/aldo-aldiero', icon: 'linkedin' },
  { label: 'Twitter', href: 'https://youtu.be/Uq7kyf1T_lk?list=RDUq7kyf1T_lk', icon: 'x' },
  { label: 'Email', href: 'mailto:aldoaldiero.work@gmail.com', icon: 'mail' },
]

export const PROJECTS: Project[] = [
  {
    id: '1',
    title: 'Prosehat',
    description: 'Healthcare and wellness platform.',
    longDescription: 'Built real-time video consultation platform with WebRTC and Next.js featuring AI chatbot triage and automated prescription generation. Implemented webhook-based notifications, data tables for doctor appointment lists, doctor dashboard for profiles and transaction history, and patient-facing menu for browsing doctors and available appointment slots. Revamped healthcare admin site using React, Vite, and ShadcnUI with Midtrans payment integration.',
    tags: ['Next.js', 'React', 'WebRTC', 'Vite', 'ShadcnUI'],
    category: 'Health',
    image: '/projects/prosehat.webp',
    featured: true,
    year: 2025,
  },
  {
    id: '2',
    title: 'Aikrut',
    description: 'B2B AI-driven Video Interview System and high-performance analytics dashboards.',
    longDescription: 'Migrated legacy React (2017) to Next.js 15 for a B2B platform, developing an AI-driven interview system with custom admin/user dashboards. Implemented secure authentication using BetterAuth with Google SSO and Google Captcha. Built test result analysis charts for assessments, personality tests, and multiple HR test types with PDF export for each candidate\'s results. Implemented RBAC for each company account to ensure secure multi-tenant access control. Set up CI/CD pipeline using Bitbucket Pipelines, Jest for unit testing, Husky for pre-commit hooks, Docker for MySQL database, and VPS hosting with dev and production environments.',
    tags: ['Next.js', 'React', 'TypeScript', 'BetterAuth', 'Docker', 'PostgreSQL', 'Bitbucket Pipelines'],
    category: 'SaaS',
    image: '/projects/aikrut.webp',
    featured: true,
    year: 2025,
  },
  {
    id: '3',
    title: 'BSI Hasanah Credit Card',
    description: 'Credit Card Form Registration and analytics flow with identity verification for a bank.',
    longDescription: 'Built secure registration and analytics flow with facial recognition and ID card OCR for automated identity verification. Implemented authentication and authorization including OAuth SSO, MFA, JWT, RBAC, OTP, and DOB verification for document encryption.',
    tags: ['Nuxt.js', 'Vue 2', 'OCR'],
    category: 'Finance',
    image: '/projects/bsi.webp',
    featured: true,
    year: 2023,
  },
  {
    id: '4',
    title: 'eDot Ecosystem (Hermes & eSuite)',
    description: 'Distribution Management System (DMS) dashboards & analytics dashboard.',
    longDescription: 'Maintained and expanded Distribution Management System (DMS) dashboards using Next.js, implementing Firebase Remote Config for feature flagging, Jest for unit testing, and RBAC for multi-tenant access control across company accounts.',
    tags: ['Next.js', 'Firebase', 'Jest'],
    category: 'SaaS',
    image: '/projects/esuite.webp',
    featured: true,
    year: 2026,
  },
  {
    id: '5',
    title: 'HAWKEYE Internal Dashboard',
    description: 'Dynamic enterprise management system for Merchants and Channels.',
    longDescription: 'Developed dynamic enterprise management system for Merchants/Channels with RBAC, reusable data-fetching logic, data tables with complex filters, and Excel import/export functionality.',
    tags: ['Vue 3', 'Nuxt.js'],
    category: 'Finance',
    image: '',
    featured: false,
    year: 2024,
  },
  {
    id: '6',
    title: 'Privy Customization Dashboard',
    description: 'CMS-driven dashboard for dynamic project styling for each companies.',
    longDescription: 'Maintained CMS-driven dashboard for dynamic styling and form management across signing document projects, including Vue 2 to Vue 3 migration. Implemented form validation using Zod and managed state with Context API.',
    tags: ['Vue 2', 'Vue 3', 'Nuxt.js', 'Zod'],
    category: 'Finance',
    image: '',
    featured: false,
    year: 2022,
  },
  {
    id: '7',
    title: 'LingoTalk & LingoJunior',
    description: 'High-performance landing pages and bilingual exam portal.',
    longDescription: 'Engineered high-performance landing pages and bilingual language exam page (Mandarin & English) focused on speed and minimal bundle size. Created analytics dashboard for test results and user performance analysis.',
    tags: ['Svelte', 'SvelteKit'],
    category: 'Education',
    image: '/projects/lingotalk.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '8',
    title: 'Skillana',
    description: 'Assessment platform for candidates, that provide the interviews for workers.',
    longDescription: 'Orchestrated legacy React (2017) to Next.js migration, resolving critical heritage bugs to ensure a stable transition. Refactored legacy functions into modern, modular components to improve maintainability and codebase scalability.',
    tags: ['Next.js', 'React', 'JavaScript'],
    category: 'SaaS',
    image: '/projects/skillana.webp',
    featured: false,
    year: 2025,
  },
  {
    id: '9',
    title: 'Android Face Liveness App',
    description: 'Camera-based face detection application for university thesis.',
    longDescription: 'Researched and developed camera-based face detection Android application using Java and Python for user authentication in mobile app, serving as university thesis project.',
    tags: ['Java', 'Python'],
    category: 'Application',
    image: '/projects/app.webp',
    featured: false,
    year: 2021,
  },
  {
    id: '10',
    title: 'CIMB Event Portal',
    description: 'High-traffic event landing page, registration form & admin dashboard.',
    longDescription: 'Developed a high-traffic landing page and admin dashboard. Provided real-time bug fixing and complex price calculation logic during a live 3-day high-stakes event period.',
    tags: ['Nuxt.js', 'Vue 2'],
    category: 'Finance',
    image: '',
    featured: false,
    year: 2022,
  },
  {
    id: '11',
    title: 'HMS Document Signing',
    description: 'Document signing portal and data analytics dashboard.',
    longDescription: 'Architected a complete document signing landing page and data analytics dashboard from the ground up using Vue.js and Nuxt.js, featuring dynamic form inputs.',
    tags: ['Nuxt.js', 'Vue 2'],
    category: 'Finance',
    image: '/projects/hms.webp',
    featured: false,
    year: 2022,
  },
]

export const SKILL_GROUPS: SkillGroup[] = [
  {
    category: 'Frontend',
    icon: 'monitor',
    skills: [
      { name: 'React', level: 95, category: 'frontend', color: '#61DAFB' },
      { name: 'Next.js', level: 95, category: 'frontend', color: '#FFFFFF' },
      { name: 'Vue.js', level: 90, category: 'frontend', color: '#42B883' },
      { name: 'Nuxt.js', level: 90, category: 'frontend', color: '#00C1DE' },
      // { name: 'Svelte', level: 70, category: 'frontend', color: '#FF3E00' },
      { name: 'SvelteKit', level: 70, category: 'frontend', color: '#FF3E00' },
      // { name: 'TypeScript', level: 95, category: 'frontend', color: '#3178C6' },
      // { name: 'JavaScript', level: 95, category: 'frontend', color: '#F7DF1E' },
      // { name: 'HTML5', level: 95, category: 'frontend', color: '#E34F26' },
      // { name: 'CSS3/SCSS', level: 90, category: 'frontend', color: '#1572B6' },
      { name: 'Tailwind CSS', level: 95, category: 'frontend', color: '#06B6D4' },
      { name: 'ShadcnUI', level: 90, category: 'frontend', color: '#FFFFFF' },
      // { name: 'Material UI', level: 85, category: 'frontend', color: '#007FFF' },
      { name: 'Vuetify', level: 85, category: 'frontend', color: '#1867C0' },
      { name: 'NuxtUI', level: 85, category: 'frontend', color: '#00DC82' },
      // { name: 'Responsive Design', level: 95, category: 'frontend', color: '#FFFFFF' },
    ],
  },
  {
    category: 'Backend',
    icon: 'wrench',
    skills: [
      { name: 'Node.js', level: 80, category: 'backend', color: '#339933' },
      { name: 'Express.js', level: 80, category: 'backend', color: '#000000' },
      { name: 'RESTful APIs', level: 90, category: 'backend', color: '#FFFFFF' },
      { name: 'PostgreSQL', level: 70, category: 'backend', color: '#4169E1' },
      { name: 'Java', level: 70, category: 'backend', color: '#ED8B00' },
      { name: 'PHP', level: 70, category: 'backend', color: '#777BB4' },
      { name: 'Python', level: 60, category: 'backend', color: '#3776AB' },
    ],
  },
  {
    category: 'Tools & Testing',
    icon: 'settings',
    skills: [
      { name: 'Jest', level: 90, category: 'backend', color: '#C21325' },
      { name: 'Vite', level: 85, category: 'frontend', color: '#646CFF' },
      { name: 'Git', level: 90, category: 'backend', color: '#F05032' },
      { name: 'Firebase Remote Config', level: 80, category: 'backend', color: '#FFCA28' },
      { name: 'Sentry.io', level: 80, category: 'backend', color: '#362D59' },
      { name: 'Datadog', level: 75, category: 'backend', color: '#632CA6' },
      { name: 'Bitbucket Pipelines', level: 80, category: 'backend', color: '#0052CC' },
      { name: 'Docker', level: 75, category: 'backend', color: '#2496ED' },
      { name: 'Husky', level: 80, category: 'backend', color: '#C4A34F' },
    ],
  },
  {
    category: 'Security & Auth',
    icon: 'shield',
    skills: [
      { name: 'OAuth SSO', level: 85, category: 'backend', color: '#FFFFFF' },
      { name: 'MFA', level: 85, category: 'backend', color: '#FFFFFF' },
      { name: 'JWT', level: 90, category: 'backend', color: '#FFFFFF' },
      { name: 'RBAC', level: 90, category: 'backend', color: '#FFFFFF' },
      { name: 'OTP Verification', level: 85, category: 'backend', color: '#FFFFFF' },
      { name: 'CSRF/XSS Prevention', level: 85, category: 'backend', color: '#FFFFFF' },
      { name: 'Data Encryption', level: 85, category: 'backend', color: '#FFFFFF' },
    ],
  },
  {
    category: 'Integrations',
    icon: 'link',
    skills: [
      { name: 'Midtrans API', level: 80, category: 'backend', color: '#FF3B30' },
      { name: 'OCR/Facial Recognition', level: 75, category: 'backend', color: '#FFFFFF' },
      { name: 'SEO Optimization', level: 90, category: 'softskills', color: '#A259FF' },
      { name: 'Websocket', level: 80, category: 'backend', color: '#FFFFFF' },
      { name: 'WebRTC', level: 80, category: 'backend', color: '#FFFFFF' },
      { name: 'Feature Flags', level: 80, category: 'backend', color: '#FFFFFF' },
    ],
  },
  {
    category: 'Methodologies',
    icon: 'users',
    skills: [
      { name: 'Agile/Scrum', level: 90, category: 'softskills', color: '#A259FF' },
      { name: 'Unit Testing', level: 90, category: 'softskills', color: '#A259FF' },
      { name: 'API Design', level: 90, category: 'softskills', color: '#A259FF' },
      { name: 'Performance Tuning', level: 90, category: 'softskills', color: '#A259FF' },
      { name: 'Microservices', level: 85, category: 'softskills', color: '#A259FF' },
    ],
  },
]

export const EXPERIENCES: Experience[] = [
  {
    id: '1',
    company: 'PT. Elektronik Distribusi Otomatisasi Terkemuka',
    role: 'Frontend Engineer',
    duration: 'Dec 2025 – Jun 2026',
    startDate: '2025-12',
    endDate: '2026-06',
    type: 'full-time',
    description: [
      'Engineered scalable web platform features using Next.js and TypeScript, including data tables with Excel import, detail pages, complex filters, and validated forms using Zod, all built with company\'s existing component library to accelerate development and reduce time-to-market.',
      'Maintained and implemented customized RBAC for each company using the existing company dashboard, ensuring granular access control and secure multi-tenant management.',
      'Enhanced application observability and release control by implementing feature flags via Firebase Remote Config and monitoring with Sentry.io and Datadog.',
      'Increased code reliability and reduced production bugs by implementing a comprehensive unit testing suite using Jest, while optimizing API consumption through request caching and redesigned parameter integration for faster page loads.',
      'Collaborated within cross-functional squads to resolve critical frontend bottlenecks, leveraging Context API and Redux for efficient state management to enhance overall application stability and user retention.',
    ],
    technologies: ['Next.js', 'TypeScript', 'Zod', 'Firebase', 'Sentry.io', 'Datadog', 'Jest', 'Redux'],
  },
  {
    id: '2',
    company: 'UMG Idealab',
    role: 'Senior Web Developer',
    duration: 'Dec 2024 – Dec 2025',
    startDate: '2024-12',
    endDate: '2025-12',
    type: 'full-time',
    description: [
      'Architected and delivered fullstack solutions for high-profile platforms (Widya Imersif, Genomic, Skilloka) using React, Next.js, and Node.js, ensuring seamless end-to-end functionality from database to UI.',
      'Built a real-time video consultation platform for health startups using WebRTC, Websocket and Next.js, enabling secure, low-latency doctor-patient communication with AI-powered chatbot triage and automated prescription generation for patients.',
      'Led a team of developers and served as the key technical bridge between the CTO and clients, translating business requirements into actionable technical roadmaps and communicating progress, constraints, and decisions across stakeholders.',
      'Led full migration of legacy React applications to Next.js, leveraging server-side rendering and static generation to significantly improve performance, SEO, and developer experience, while refactoring legacy codebases into modern, modular components for enhanced scalability and maintainability.',
    ],
    technologies: ['React', 'Next.js', 'Node.js', 'WebRTC', 'Websocket'],
  },
  {
    id: '3',
    company: 'Privy',
    role: 'Intermediate Frontend Engineer',
    duration: 'Dec 2021 – Nov 2024',
    startDate: '2021-12',
    endDate: '2024-11',
    type: 'full-time',
    description: [
      'Developed and deployed complex enterprise SaaS platforms and dashboards using Vue.js and Nuxt.js, adhering to strict security and performance standards.',
      'Architected and deployed a digital document signing platform in a microservice environment with end-to-end encryption and audit trails for legally compliant e-signature workflows.',
      'Implemented robust authentication and authorization including OAuth SSO, MFA, JWT, RBAC, OTP, DOB verification, and liveness detection for face recognition to secure user onboarding and encrypted document access.',
      'Remediated critical frontend vulnerabilities (XSS, CSRF, clickjacking, insecure cookie handling, exposed client-side data) identified during penetration testing and UAT, strengthening overall application security posture.',
      'Accelerated delivery cycles using Agile methodologies, collaborating across Backend, Frontend, UI/UX, Product Management, and QA teams to manage multiple concurrent project streams within single sprints.',
    ],
    technologies: ['Vue.js', 'Nuxt.js', 'OAuth SSO', 'MFA', 'JWT', 'RBAC'],
  },
  {
    id: '4',
    company: 'LingoTalk',
    role: 'Junior Frontend Engineer',
    duration: 'Jan 2021 – Dec 2021',
    startDate: '2021-01',
    endDate: '2021-12',
    type: 'full-time',
    description: [
      'Architected interactive frontend interfaces using Svelte and SvelteKit, delivering a lightweight and highly responsive user experience.',
      'Built and maintained platform landing pages, bilingual language test pages (Mandarin & English), and an analytics dashboard for test results and user analysis.',
      'Rapidly resolved critical UI bugs and implemented feature enhancements based on user feedback.',
    ],
    technologies: ['Svelte', 'SvelteKit'],
  },
]

export const EDUCATION: Education[] = [
  {
    id: '1',
    degree: 'Bachelor of Information Technology',
    institution: 'Universitas Atma Jaya Yogyakarta',
    year: '2021',
    location: 'Yogyakarta, Indonesia',
    description: [
      'GPA: 3.77/4.0',
      'Won 3rd place in university programming competition in 2017.',
    ],
  },
]

export const TESTIMONIALS: Testimonial[] = []

export const OWNER = {
  name: 'Aldo Aldiero',
  title: 'Senior Web Developer',
  tagline: 'Results-driven Fullstack Engineer with 5+ years of experience building scalable, high-performance web applications with a strong focus on frontend architecture.',
  bio: 'Results-driven Fullstack Engineer with 5+ years of experience specializing in building scalable, high-performance web applications with a strong focus on frontend architecture. Proficient in Next.js, Nuxt.js, and SvelteKit, backed by solid backend expertise in Node.js and PostgreSQL.\n\n Proven track record of optimizing application performance by 40%, migrating legacy systems to modern frameworks, and delivering end-to-end solutions from database design to pixel-perfect interfaces. Adept at collaborating in cross-functional agile squads to drive business growth and enhance user engagement.',
  location: 'Yogyakarta, Indonesia',
  email: 'aldoaldiero.work@gmail.com',
  availability: 'Open to opportunities',
  resumeUrl: '/resume.pdf',
}
